title: Diccionario LSP al Español
author: The Dictionary LSP to Spanish Team
logo: ./assets/pucp_logo.png
only_build_toc_files: true

sphinx:
  config:
    autodoc_mock_imports: ["wx"]
  extra_extensions:
    - numpydoc

execute:
  execute_notebooks: "off"

html:
  extra_navbar: ""
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <div>Powered by <a href="https://jupyterbook.org/">Jupyter Book</a>.</div>

repository:
  url: https://github.com/JoeNatan30/SpanishToPSLTranslationService
  path_to_book: docs
  branch: master

